exec(open('/tmp/cc501/nested/x/h.py').read())
s.open_scene(c,sc)
for g in ("G5","G8","G3"): c.send("group.expand",{"id":I[g],"expanded":False})
c.send("view.set",{"pps":50,"block_height":16,"scroll_x":0,"scroll_y":0}); s.settle(c,500)
c.send("view.reveal",{"ids":[I['B1']]}); s.settle(c,300)
g=s.geometry(c)
x,y=s.find_zone(c,I['B1'],"move")
_,ty,_,_=s.block_rect(c,I['G9'],g); dy=ty+g['bh']*0.75-y
print("target y",ty+g['bh']*0.75,"vh",g['vh'])
b=s.items_state(c); tb=s.tree_index(json.loads(b)); n0=count()
c.send("input.drag",{"x":x,"y":y,"dx":0,"dy":dy,"duration_ms":500,"release":False}); s.settle(c,300)
s.snapshot(c,OUT+"D2_held.png"); print("model untouched",s.items_state(c)==b)
c.send("input.release"); s.settle(c,600)
ta=s.tree_index(c.send('project.get_state')['items'])
for k,v in I.items():
    if tb.get(v)!=ta.get(v): print(k,tb[v],'->',ta.get(v))
print("count",n0,count()); s.snapshot(c,OUT+"D2_after.png")
c.send("edit.undo"); s.settle(c,500); print("undo ok",s.items_state(c)==b)
